In [22]:
# pip install panads
# pip install numpy
import numpy as np
import pandas as pd

In [25]:
data=np.arange(24).reshape(4,6)
data

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [27]:
type(data)

numpy.ndarray

In [29]:
data=np.arange(30,60).reshape(5,6)
data

array([[30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [31]:
data2=np.linspace(20,10,4)
data2

array([20.        , 16.66666667, 13.33333333, 10.        ])

In [33]:
np.random.randint(10)

1

In [45]:
df=pd.DataFrame(data)
data

array([[30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [57]:

df.data,index=['row1','row2','row3','row4','row5']
cloumn['cloumn1','cloumn2','cloumn3','cloumn4','cloumn5']

ValueError: too many values to unpack (expected 2)

In [49]:
df.shape

(5, 6)

In [51]:
df.head

<bound method NDFrame.head of     0   1   2   3   4   5
0  30  31  32  33  34  35
1  36  37  38  39  40  41
2  42  43  44  45  46  47
3  48  49  50  51  52  53
4  54  55  56  57  58  59>

In [53]:
df.tail

<bound method NDFrame.tail of     0   1   2   3   4   5
0  30  31  32  33  34  35
1  36  37  38  39  40  41
2  42  43  44  45  46  47
3  48  49  50  51  52  53
4  54  55  56  57  58  59>

In [55]:
df.sample()

0   1   2   3   4   5
2  42  43  44  45  46  47

In [61]:
df.describe()

0          1          2          3          4          5
count   5.000000   5.000000   5.000000   5.000000   5.000000   5.000000
mean   42.000000  43.000000  44.000000  45.000000  46.000000  47.000000
std     9.486833   9.486833   9.486833   9.486833   9.486833   9.486833
min    30.000000  31.000000  32.000000  33.000000  34.000000  35.000000
25%    36.000000  37.000000  38.000000  39.000000  40.000000  41.000000
50%    42.000000  43.000000  44.000000  45.000000  46.000000  47.000000
75%    48.000000  49.000000  50.000000  51.000000  52.000000  53.000000
max    54.000000  55.000000  56.000000  57.000000  58.000000  59.000000

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       5 non-null      int32
 1   1       5 non-null      int32
 2   2       5 non-null      int32
 3   3       5 non-null      int32
 4   4       5 non-null      int32
 5   5       5 non-null      int32
dtypes: int32(6)
memory usage: 252.0 bytes


In [69]:
# Generating sample Google Play Store data
data = {
    'App': [f'App_{i}' for i in range(1, 31)],
    'Category': np.random.choice(['Game', 'Productivity', 'Health', 'Education'], 30),
    'Rating': np.random.uniform(1.0, 5.0, 30).round(1),
    'Reviews': np.random.randint(1, 10000, 30),
    'Size': np.random.choice(['Varies with device', '10M', '20M', '30M'], 30),
    'Installs': np.random.choice(['1,000+', '10,000+', '50,000+', '100,000+'], 30),
    'Type': np.random.choice(['Free', 'Paid'], 30),
    'Price': np.random.choice(['0', '0.99', '1.99', '2.99', '4.99', '5.99', '9.99'], 30),
    'Content Rating': np.random.choice(['Everyone', 'Teen', 'Everyone 10+', 'Mature 17+'], 30)
}

In [71]:
data

{'App': ['App_1',
  'App_2',
  'App_3',
  'App_4',
  'App_5',
  'App_6',
  'App_7',
  'App_8',
  'App_9',
  'App_10',
  'App_11',
  'App_12',
  'App_13',
  'App_14',
  'App_15',
  'App_16',
  'App_17',
  'App_18',
  'App_19',
  'App_20',
  'App_21',
  'App_22',
  'App_23',
  'App_24',
  'App_25',
  'App_26',
  'App_27',
  'App_28',
  'App_29',
  'App_30'],
 'Category': array(['Productivity', 'Game', 'Education', 'Productivity',
        'Productivity', 'Productivity', 'Education', 'Game',
        'Productivity', 'Education', 'Game', 'Productivity',
        'Productivity', 'Education', 'Game', 'Game', 'Education',
        'Education', 'Education', 'Productivity', 'Education',
        'Productivity', 'Health', 'Productivity', 'Education',
        'Productivity', 'Productivity', 'Education', 'Education',
        'Education'], dtype='<U12'),
 'Rating': array([4.1, 2.6, 2.1, 4.4, 3.8, 3.8, 4.1, 3.5, 3.1, 2.7, 2.9, 4.4, 5. ,
        5. , 5. , 3.5, 2. , 3.3, 3.9, 3.4, 2.4, 2.1, 1.2, 1.8, 4. , 

In [73]:
data

{'App': ['App_1',
  'App_2',
  'App_3',
  'App_4',
  'App_5',
  'App_6',
  'App_7',
  'App_8',
  'App_9',
  'App_10',
  'App_11',
  'App_12',
  'App_13',
  'App_14',
  'App_15',
  'App_16',
  'App_17',
  'App_18',
  'App_19',
  'App_20',
  'App_21',
  'App_22',
  'App_23',
  'App_24',
  'App_25',
  'App_26',
  'App_27',
  'App_28',
  'App_29',
  'App_30'],
 'Category': array(['Productivity', 'Game', 'Education', 'Productivity',
        'Productivity', 'Productivity', 'Education', 'Game',
        'Productivity', 'Education', 'Game', 'Productivity',
        'Productivity', 'Education', 'Game', 'Game', 'Education',
        'Education', 'Education', 'Productivity', 'Education',
        'Productivity', 'Health', 'Productivity', 'Education',
        'Productivity', 'Productivity', 'Education', 'Education',
        'Education'], dtype='<U12'),
 'Rating': array([4.1, 2.6, 2.1, 4.4, 3.8, 3.8, 4.1, 3.5, 3.1, 2.7, 2.9, 4.4, 5. ,
        5. , 5. , 3.5, 2. , 3.3, 3.9, 3.4, 2.4, 2.1, 1.2, 1.8, 4. , 

In [75]:
type(data)

dict

In [83]:
df=pd.DataFrame(data)
df

App      Category  Rating  Reviews                Size  Installs  Type  \
0    App_1  Productivity     4.1     1366  Varies with device   50,000+  Free   
1    App_2          Game     2.6     2945                 30M   10,000+  Free   
2    App_3     Education     2.1     9395                 10M  100,000+  Paid   
3    App_4  Productivity     4.4     3305  Varies with device   50,000+  Paid   
4    App_5  Productivity     3.8     9506  Varies with device   10,000+  Paid   
5    App_6  Productivity     3.8     8902                 20M   50,000+  Free   
6    App_7     Education     4.1     8971                 10M   50,000+  Free   
7    App_8          Game     3.5     3115                 10M   10,000+  Paid   
8    App_9  Productivity     3.1     6577                 10M    1,000+  Free   
9   App_10     Education     2.7      602                 10M  100,000+  Paid   
10  App_11          Game     2.9     6947                 30M    1,000+  Paid   
11  App_12  Productivity     4.4     4048                 20M  100,000+  Free   
12  App_13  Productivity     5.0     3816                 10M   10,000+  Free   
13  App_14     Education     5.0     6406                 20M  100,000+  Free   
14  App_15          Game     5.0     5435                 10M   50,000+  Paid   
15  App_16          Game     3.5     6393                 20M  100,000+  Free   
16  App_17     Education     2.0     7588                 20M  100,000+  Free   
17  App_18     Education     3.3     1016                 30M  100,000+  Paid   
18  App_19     Education     3.9     3795  Varies with device   50,000+  Paid   
19  App_20  Productivity     3.4      380                 20M    1,000+  Free   
20  App_21     Education     2.4     4388  Varies with device    1,000+  Paid   
21  App_22  Productivity     2.1      414  Varies with device    1,000+  Paid   
22  App_23        Health     1.2     8606  Varies with device    1,000+  Paid   
23  App_24  Productivity     1.8     6462                 10M   50,000+  Free   
24  App_25     Education     4.0     4904                 30M   10,000+  Paid   
25  App_26  Productivity     4.3     2439                 10M  100,000+  Free   
26  App_27  Productivity     4.1     2334                 10M    1,000+  Free   
27  App_28     Education     1.8     8273                 10M    1,000+  Paid   
28  App_29     Education     3.6     7700                 20M   10,000+  Paid   
29  App_30     Education     3.0     3961                 30M   10,000+  Paid   

   Price Content Rating  
0   4.99     Mature 17+  
1      0   Everyone 10+  
2   4.99   Everyone 10+  
3   2.99     Mature 17+  
4   2.99     Mature 17+  
5      0   Everyone 10+  
6   1.99           Teen  
7   0.99       Everyone  
8   0.99           Teen  
9   1.99       Everyone  
10  1.99       Everyone  
11  5.99     Mature 17+  
12     0     Mature 17+  
13  5.99           Teen  
14  9.99           Teen  
15     0           Teen  
16  0.99   Everyone 10+  
17  2.99   Everyone 10+  
18  4.99   Everyone 10+  
19  1.99       Everyone  
20     0   Everyone 10+  
21  0.99       Everyone  
22  5.99           Teen  
23     0       Everyone  
24     0           Teen  
25  0.99           Teen  
26     0           Teen  
27  2.99       Everyone  
28  2.99     Mature 17+  
29  4.99     Mature 17+

In [85]:
df.describe()

Rating      Reviews
count  30.000000    30.000000
mean    3.363333  4999.633333
std     1.031398  2883.814123
min     1.200000   380.000000
25%     2.625000  2987.500000
50%     3.500000  4646.000000
75%     4.100000  7427.750000
max     5.000000  9506.000000

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   App             30 non-null     object 
 1   Category        30 non-null     object 
 2   Rating          30 non-null     float64
 3   Reviews         30 non-null     int32  
 4   Size            30 non-null     object 
 5   Installs        30 non-null     object 
 6   Type            30 non-null     object 
 7   Price           30 non-null     object 
 8   Content Rating  30 non-null     object 
dtypes: float64(1), int32(1), object(7)
memory usage: 2.1+ KB


In [89]:
df.head

<bound method NDFrame.head of        App      Category  Rating  Reviews                Size  Installs  Type  \
0    App_1  Productivity     4.1     1366  Varies with device   50,000+  Free   
1    App_2          Game     2.6     2945                 30M   10,000+  Free   
2    App_3     Education     2.1     9395                 10M  100,000+  Paid   
3    App_4  Productivity     4.4     3305  Varies with device   50,000+  Paid   
4    App_5  Productivity     3.8     9506  Varies with device   10,000+  Paid   
5    App_6  Productivity     3.8     8902                 20M   50,000+  Free   
6    App_7     Education     4.1     8971                 10M   50,000+  Free   
7    App_8          Game     3.5     3115                 10M   10,000+  Paid   
8    App_9  Productivity     3.1     6577                 10M    1,000+  Free   
9   App_10     Education     2.7      602                 10M  100,000+  Paid   
10  App_11          Game     2.9     6947                 30M    1,000+  Paid  

In [91]:
df.tail

<bound method NDFrame.tail of        App      Category  Rating  Reviews                Size  Installs  Type  \
0    App_1  Productivity     4.1     1366  Varies with device   50,000+  Free   
1    App_2          Game     2.6     2945                 30M   10,000+  Free   
2    App_3     Education     2.1     9395                 10M  100,000+  Paid   
3    App_4  Productivity     4.4     3305  Varies with device   50,000+  Paid   
4    App_5  Productivity     3.8     9506  Varies with device   10,000+  Paid   
5    App_6  Productivity     3.8     8902                 20M   50,000+  Free   
6    App_7     Education     4.1     8971                 10M   50,000+  Free   
7    App_8          Game     3.5     3115                 10M   10,000+  Paid   
8    App_9  Productivity     3.1     6577                 10M    1,000+  Free   
9   App_10     Education     2.7      602                 10M  100,000+  Paid   
10  App_11          Game     2.9     6947                 30M    1,000+  Paid  

In [93]:
df.sample()

App      Category  Rating  Reviews Size Installs  Type Price  \
12  App_13  Productivity     5.0     3816  10M  10,000+  Free     0   

   Content Rating  
12     Mature 17+

In [101]:
df[['App','Price','Type']]

App Price  Type
0    App_1  4.99  Free
1    App_2     0  Free
2    App_3  4.99  Paid
3    App_4  2.99  Paid
4    App_5  2.99  Paid
5    App_6     0  Free
6    App_7  1.99  Free
7    App_8  0.99  Paid
8    App_9  0.99  Free
9   App_10  1.99  Paid
10  App_11  1.99  Paid
11  App_12  5.99  Free
12  App_13     0  Free
13  App_14  5.99  Free
14  App_15  9.99  Paid
15  App_16     0  Free
16  App_17  0.99  Free
17  App_18  2.99  Paid
18  App_19  4.99  Paid
19  App_20  1.99  Free
20  App_21     0  Paid
21  App_22  0.99  Paid
22  App_23  5.99  Paid
23  App_24     0  Free
24  App_25     0  Paid
25  App_26  0.99  Free
26  App_27     0  Free
27  App_28  2.99  Paid
28  App_29  2.99  Paid
29  App_30  4.99  Paid

In [103]:
df.shape

(30, 9)

In [107]:
df['Size'].unique()

array(['Varies with device', '30M', '10M', '20M'], dtype=object)

In [109]:
df['Price'].unique()

array(['4.99', '0', '2.99', '1.99', '0.99', '5.99', '9.99'], dtype=object)

In [111]:
df['Type'].unique()

array(['Free', 'Paid'], dtype=object)

In [113]:
df.isnull()

App  Category  Rating  Reviews   Size  Installs   Type  Price  \
0   False     False   False    False  False     False  False  False   
1   False     False   False    False  False     False  False  False   
2   False     False   False    False  False     False  False  False   
3   False     False   False    False  False     False  False  False   
4   False     False   False    False  False     False  False  False   
5   False     False   False    False  False     False  False  False   
6   False     False   False    False  False     False  False  False   
7   False     False   False    False  False     False  False  False   
8   False     False   False    False  False     False  False  False   
9   False     False   False    False  False     False  False  False   
10  False     False   False    False  False     False  False  False   
11  False     False   False    False  False     False  False  False   
12  False     False   False    False  False     False  False  False   
13  False     False   False    False  False     False  False  False   
14  False     False   False    False  False     False  False  False   
15  False     False   False    False  False     False  False  False   
16  False     False   False    False  False     False  False  False   
17  False     False   False    False  False     False  False  False   
18  False     False   False    False  False     False  False  False   
19  False     False   False    False  False     False  False  False   
20  False     False   False    False  False     False  False  False   
21  False     False   False    False  False     False  False  False   
22  False     False   False    False  False     False  False  False   
23  False     False   False    False  False     False  False  False   
24  False     False   False    False  False     False  False  False   
25  False     False   False    False  False     False  False  False   
26  False     False   False    False  False     False  False  False   
27  False     False   False    False  False     False  False  False   
28  False     False   False    False  False     False  False  False   
29  False     False   False    False  False     False  False  False   

    Content Rating  
0            False  
1            False  
2            False  
3            False  
4            False  
5            False  
6            False  
7            False  
8            False  
9            False  
10           False  
11           False  
12           False  
13           False  
14           False  
15           False  
16           False  
17           False  
18           False  
19           False  
20           False  
21           False  
22           False  
23           False  
24           False  
25           False  
26           False  
27           False  
28           False  
29           False

In [115]:
df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
dtype: int64

In [119]:
df['Price']=df['Price'].replace('free''0')
df['Price']

C:\Users\PRINCESS BHARTI\AppData\Local\Temp\ipykernel_9276\2308916664.py:1: FutureWarning: Series.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  df['Price']=df['Price'].replace('free''0')


0     4.99
1        0
2     4.99
3     2.99
4     2.99
5        0
6     1.99
7     0.99
8     0.99
9     1.99
10    1.99
11    5.99
12       0
13    5.99
14    9.99
15       0
16    0.99
17    2.99
18    4.99
19    1.99
20       0
21    0.99
22    5.99
23       0
24       0
25    0.99
26       0
27    2.99
28    2.99
29    4.99
Name: Price, dtype: object